name: Bayut WhatsApp Alerts

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run main.py
        env:
          ULTRA_INSTANCE_ID: ${{ secrets.ULTRA_INSTANCE_ID }}
          ULTRA_TOKEN: ${{ secrets.ULTRA_TOKEN }}
          WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
          SENT_LINKS: ${{ secrets.SENT_LINKS }}
        run: python main.py
